apiVersion: v1
kind: Service
metadata:
  name: cloud-android-runner
  labels:
    app: cloud-android-runner
spec:
  type: LoadBalancer
  selector:
    app: cloud-android-runner
  ports:
  - name: vnc
    port: 6080
    targetPort: 6080
    protocol: TCP
  - name: adb
    port: 5555
    targetPort: 5555
    protocol: TCP
